### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by pseudoforceyt** [kubo6472/kubo6472#1]
Problem:
![image](https://user-images.githubusercontent.com/70620481/129465536-08f105da-9e7c-4122-af62-661ab1ad308b.png)

Steps for Reproduction:

1.  Open preferred browser
2.  Go to [https://git.jakubdobos.eu/jakub](https://git.jakubdobos.eu/jakub)
3.  Site is not reachable

**Comment by kubo6472** [comment]
Hello. thanks for stopping by. I host the site myself and am currently working on some OS stuff, so it is an unscheduled maintenance. Will close when up :)

**Comment by kubo6472** [comment]
The site is up. I will be waiting with another downtime after you get what you need. So please let me know when that’s done :)
